### ISSUE TITLE
Stop time if commit dialog is open

### ISSUE THREAD

**Issue by ollin** [dkandalov/limited-wip#10]
Scenario:

Using the clock as the constraint.

editing -> finished work -> open commit dialog one second before the time runs out - add 2 seconds -> limitWip reverts -> change lost 

Improvement:

Stop the clock. (not reset) Continue the clock if the dialog closes without commit

**Comment by ollin** [comment]
can use "Stop auto-revert" - Shortcut

**Comment by dkandalov** [comment]
Implemented as:
 - open commit dialog one second before the time runs out - add 2 seconds 
 - no auto-revert, timer reaches timeout but doesn't start over
 - when commit dialog closes auto-revert is done (if all changes were committed, there is nothing to revert) and timer starts ticking
