### ISSUE TITLE
Relaxed TCR

### ISSUE THREAD

**Issue by yjaaidi** [dkandalov/limited-wip#20]
Hi @dkandalov ,

As suggested by Thomas Deniffel here https://medium.com/@tdeniffel/tcr-variants-test-commit-revert-bf6bd84b17d3, it would be nice to only revert production code and not tests.

I think it would be nice to be able to define a whitelist or/and blacklist of files that should be reverted by TCR using wildcards or regex or both.

I guess that wildcard or regex blacklist would be the priority.

Thanks Dmitry!

**Comment by dkandalov** [comment]
In IJ IDEs test folders are usually (but of course not always) are marked as `test` in project settings. I think it might be a simpler thing to do for now 🤔

**Comment by yjaaidi** [comment]
Hi Dmitry,

If it's a quick win, we could start with that but in the JavaScript world
for example, it's quiet common to put test files (.spec.ts) next to the
tested code.

That's why I thought it would be better to let people choose.

**Comment by dkandalov** [comment]
Done in plugin version 0.3.3 (it will be available in couple days after jetbrains approves it).

**Comment by yjaaidi** [comment]
Cool!!! Thank you very much!!!
