### ISSUE TITLE
Add a "I'm being disturbed" button to stop the timer.

### ISSUE THREAD

**Issue by jpbelang** [dkandalov/limited-wip#23]
At work, I'm interrupted with some frequency and I'd rather not have to artificially bump up the time
of my auto-revert.  Having this button could help avoid doing this.  

Maybe a popup when you click on the countdown ?  

Have I told you how much I'm enjoying this plugin ? :-)

**Comment by dkandalov** [comment]
The timer should **pause** now after clicking on auto-revert widget in IDE toolbar and **un-pause** on the next click. 

There is currently no IDE action for this, only clicking (the motivation is to discourage the behaviour by making it a bit harder, i.e. there's not keyboard shortcut). Give a shout if you have do it so often that it's worth creating an action with shortcut :)

This should work starting from [v0.3.6](https://github.com/dkandalov/limited-wip/releases/tag/v0.3.6) once it's approved by jetbrains.
