### ISSUE TITLE
Plugin "Limited WIP" is incompatible with this installation

### ISSUE THREAD

**Issue by hrules6872** [dkandalov/limited-wip#5]
Is it Android Studio (based on an IntelliJ IDE) compatible?

**Comment by dkandalov** [comment]
It should be, which version are you using?

**Comment by hrules6872** [comment]
I'm using AS 1.5 which is based on 141.+ build ... but sorry for opening this issue, I've just seen that older version 0.2.2 is compatible :)

**Comment by dkandalov** [comment]
Ok :) I try to keep plugin code as backward compatible as possible but there are breaking API changes, so the only option is to have two branches which is too much effort.

Also just to let you know, the old plugin had performance issues for large changes https://github.com/dkandalov/limited-wip/releases/tag/v0.2.5
